In [30]:
import numpy as np
import pandas as pd
from nltk import *

In [31]:
df=pd.read_csv('tamil_train.csv')

In [32]:
df.head()

movie vara level la Erika poguthu  Not_offensive
0  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil
1          Padam nalla comedy padama irukum polaye..  Not_offensive
2  karthick subburaj anne .... intha padam vetri ...  Not_offensive
3  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive
4  ippo intha trailer ah parkuravana oru like pod...  Not_offensive

In [33]:
df.Not_offensive.unique() 

array(['not-Tamil', 'Not_offensive', 'Offensive_Targeted_Insult_Other',
       'Offensive_Targeted_Insult_Group', 'Offensive_Untargetede',
       'Offensive_Targeted_Insult_Individual'], dtype=object)

In [34]:
df.shape

(35138, 2)

In [35]:
df1=pd.DataFrame({"movie vara level la Erika poguthu":["movie vara level la Erika poguthu"],
                 "Not_offensive":["Not_offensive"]})

In [36]:
df1.head()

movie vara level la Erika poguthu  Not_offensive
0  movie vara level la Erika poguthu  Not_offensive

In [37]:
data=df1.append(df, ignore_index = True)

In [38]:
data.head()

movie vara level la Erika poguthu  Not_offensive
0                  movie vara level la Erika poguthu  Not_offensive
1  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil
2          Padam nalla comedy padama irukum polaye..  Not_offensive
3  karthick subburaj anne .... intha padam vetri ...  Not_offensive
4  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive

In [39]:
data1=data.rename(columns={"movie vara level la Erika poguthu": "text", "Not_offensive": "label"})

In [40]:
data1.shape

(35139, 2)

In [41]:
data1.head()

text          label
0                  movie vara level la Erika poguthu  Not_offensive
1  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil
2          Padam nalla comedy padama irukum polaye..  Not_offensive
3  karthick subburaj anne .... intha padam vetri ...  Not_offensive
4  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive

In [42]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data1['Label']=labelencoder.fit_transform(data1['label'])

In [43]:
data1.head()

text          label  Label
0                  movie vara level la Erika poguthu  Not_offensive      0
1  I love Ajith Kumar Vivegam movie inki mjy bht ...      not-Tamil      5
2          Padam nalla comedy padama irukum polaye..  Not_offensive      0
3  karthick subburaj anne .... intha padam vetri ...  Not_offensive      0
4  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  Not_offensive      0

In [44]:
data1['Label'].value_counts()

0    25425
4     2906
1     2557
2     2343
5     1454
3      454
Name: Label, dtype: int64

In [45]:
y=[]
y=data1['Label'].values
y

array([0, 5, 0, ..., 0, 5, 0])

In [46]:
X=[]
X=data1['text'].values
X[0]

'movie vara level la Erika poguthu'

In [47]:
import tensorflow as tf
import nltk

In [48]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\DEVANSH
[nltk_data]     JAIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
from nltk.corpus import stopwords
stopwords=stopwords.words("english")
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [21]:
nltk.download('punkt')
data1['text_token'] = data1['text'].apply(lambda x: word_tokenize(x))

[nltk_data] Downloading package punkt to C:\Users\DEVANSH
[nltk_data]     JAIN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [22]:
data1

text  \
0                      movie vara level la Erika poguthu   
1      I love Ajith Kumar Vivegam movie inki mjy bht ...   
2              Padam nalla comedy padama irukum polaye..   
3      karthick subburaj anne .... intha padam vetri ...   
4      கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁   
5      ippo intha trailer ah parkuravana oru like pod...   
6      En thalaivan yogi babu irukkaar. Padam vera le...   
7             Nerkonda parvai...  Sema sema sema trailer   
8         ஏய் இது 96 யார் ஏமாத்தறீங்க? செம பின்னிட்டீங்க   
9      படம் கண்டிப்பாக வெற்றி பெற வேண்டும் செம்ம vara...   
10     Correct. Enga apa military da oodi vilaiyada s...   
11               Dislike pottavan ratham khaki dha savan   
12     ANANDHI ARMY HIT LIKE!! Ennayum ipdi aakitinga...   
13     Thalaivaa mass nadipin nayagan surya anna fans...   
14     இந்த படம் கண்டிப்பாக வெற்றியடைய வேண்டும் என வா...   
15     Hit like if anybody laughed during this 1.06 ....   
16                   I Love vijay Anna, u r so cute anna   
17     Dei Rajini pavam da ne varaven poraven ellam k...   
18     செட்டியார் இன மக்கள் சார்பாக எனது சொந்த செலவில...   
19                       Dhanush fans hit like here.....   
20     Dey dey deyyy,, loosu pasangala,, munna pinna ...   
21              aathii yenna pa different aah eruku sama   
22       Viswasam teaser Ku aprm yarllam inga vanteenga?   
23     Intha maari comments ku like kekuravangala ind...   
24     250 k likes ineram sila arivuketta pundaika it...   
25     Ellam okay than....but antha ponnu aasa pattu ...   
26     Short film ah yum vittu vakalaya... Enada pann...   
27                                   Super  i am waiting   
28                       Any Nani and Surya mutual fans?   
29     தமிழ் நாட்ல இருக்குற சாதிய பைத்தியகார கூதியானு...   
...                                                  ...   
35109  இந்த படத்தை தடுக்க நினைப்பதும் தண்டவாளத்தில் த...   
35110  Ippo dhan theriyudhu pullingo Mela ellarum evl...   
35111  hair style very super punch super ana evaru ya...   
35112  கழிவறை சுத்தம் செய்வதற்கும் வீட்டை சுத்தம் செய...   
35113  Trailer link maximum share big members Telagra...   
35114  GVP Acting Bathila Music podalam ...athula tha...   
35115  Trailer pakurathu munadi comment and like pana...   
35116  இந்த நேரத்தில் இந்த படம் தேவையா ? இந்து மாதத்த...   
35117                  Pwoli  rakshit shetty kerala fans   
35118  vaa thala ini namma neram dhaan  now its 420k ...   
35119                         Indha trailer ha ha ha ha.   
35120  வணக்கம் மாப்ள சேலத்துல இருந்து... படம் வெற்றி ...   
35121                Any one After siriki promo hit like   
35122  Suyama sinthikka therinjavan thaan HERO...But ...   
35123  pakka vj anna.....uyir rasigan.... #thalapathy...   
35124  ajith thaathaa un movie nalla illa very very k...   
35125                    Karthi die heartfan  sunya fan🤗   
35126  திருவாரூர் மாவட்ட தேவேந்திர குல வேளாளர் சார்பா...   
35127  🤣🤣🤣Maran waiting la panavendam poi saavunga Aj...   
35128           Serial actres Sathya ku oru like potunga   
35129  Indha Kalatholo Siva Karthikeyan Nadike Mudiyadhu   
35130  Naan parha ajith filmle. Entha film miga mosam...   
35131                     Vijay sethupathi fans hit like   
35132   Thala ulllaipa uyirvu ku rolemodelll nenka thala   
35133  inda pathi like thala fans um thandrukanga da ...   
35134  Trending number #2 idhukku nammalam karanamnu ...   
35135  Movie script super, athuvum HIP HOP Tamizha mu...   
35136                       Just 3k likes for 300k likes   
35137                          Aaloo le lo. Kanda le lo.   
35138  நாமக்கல் மாவட்டம்  வன்னியர் சார்பாக திரௌபதி பட...   

                                      label  Label  \
0                             Not_offensive      0   
1                                 not-Tamil      5   
2                             Not_offensive      0   
3                             Not_offensive      0   
4                             Not_offensive      0   
5      

In [23]:
k=np.array(data1.text.values)
k.shape

(35139,)

In [24]:
from nltk.tokenize import TweetTokenizer
from sklearn.feature_extraction.text import CountVectorizer
tweet_tokenizer = TweetTokenizer()
vectorizer = CountVectorizer(analyzer="word", tokenizer=tweet_tokenizer.tokenize, max_features = 4000)
X_train = vectorizer.fit_transform(k).toarray()

In [25]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
X_train.shape

(35139, 4000)

In [27]:
p=data1['text']
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')  #count vectorization
count_vect.fit(data1['text'])      
x_train_count =  count_vect.transform(p)
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect= TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}')      #tfidf
tfidf_vect.fit(data1['text'])

x_train_tfidf =  tfidf_vect.transform(p)
x_train_tfidf.toarray().shape

(35139, 47913)

In [29]:
x_train_count.tocsc().toarray().shape

(35139, 47913)